# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f30a3c824afd964e6a91cc59047ae54"
application_url = "https://example.com"
embedded = true
name = "test-hux-1"
handle = "test-hux-1"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ankush-work.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/updated"]
  uri = "/api/webhooks/orderchanged"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/webhooks"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_shopify_payments_payouts,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[pos]
embedded = false
